### ISSUE TITLE
GMP core on _gmpn_copyi call

### ISSUE THREAD

**Issue by CHUK-ANDREW** [ShiftMediaProject/gmp#10]
GMP core on _gmpn_copyi call. This happens on 10 years old AMD Phenom II X4 910e. 

The exception code 0xc000001d means:
NTSTATUS message for 0xc000001d (3221225501): {EXCEPTION} Illegal Instruction An attempt was made to execute an illegal instruction.

main!_gmpn_copyi+0x198:
00007ff7`adf48958 660f3a0ffe08    palignr xmm7,xmm6,8
0:000> k
 # Child-SP          RetAddr           Call Site
00 0000009c`d17ef4c0 00000000`00000000 main!_gmpn_copyi+0x198 [C:\gmp\gmp-6.2.0\SNP\mpn\x86_64\copyi.s @ 222]

Possibly the problem is related to CPU instructions FMA3 and AVX, because both instructions are not available on this host as I can see via CPU-Z.

for e.g. AMD FX-6200 (since 2012) got FMA3 and AVX and functionality works without any issue

## Your Environment
* Version Used:
GMP 6.2.0 (lib)
* Operating System and Version:
Windows Server 2016
* Compiler and Version(s):
Visual Studio 2019
* Processor:
AMD Phenom II X4 910e (This CPU has no AVX and FMA4 instructions )

## Possible Fix
Disable copyi.s optimization

**Comment by Sibras** [comment]
The 64bit version of gmp requires SSSE3 or newer instruction support (for performance reasons).

The 32bit version has support for older cpus if you want pre-SSSE3 capability.

**Comment by CHUK-ANDREW** [comment]
Thanks a lot for your answer. I have already add check if CPU instructions present. So this seams works for me.

**Comment by MingruiZhangW** [comment]
Hi @Sibras ,

If possible, do you know whether there is an option to remove SSSE3 or newer instruction support while maintaining the 64bit version? (For SMP)

Thanks

**Comment by Sibras** [comment]
If using the supplied Visual Studio projects then you will have to manually edit the project yourself. Remove the offending asm file and if memory serves there is a preprocessor define in config.h that corresponds to each available asm optimised function. For each function yo8u disable you will need to undef the corresponding define in config.

**Comment by MingruiZhangW** [comment]
Thanks, I will give that s shot!
