### ISSUE TITLE
libgmp.lib(invert_limb_table.obj) warning LNK4078: multiple '.rdata' sections found with different attributes (C0400040)

### ISSUE THREAD

**Issue by lion123lion2003** [ShiftMediaProject/gmp#13]
libgmp.lib(invert_limb_table.obj) warning LNK4078: multiple '.rdata' sections found with different attributes (C0400040)
## Context

I am try Cgal with mpfr and gmp. It report the above warning when link the executable.

## Your Environment

* Version Used: latest version 6.2.1_4
* Operating System and Version: windows 10 Pro 1803
* Compiler and Version(s): VS 2019 16.11.14

**Comment by Sibras** [comment]
Thats a known warning that can just be ignored (it doesnt do anything)

**Comment by lion123lion2003** [comment]
Good to know we can just ignore it.
