### ISSUE TITLE
mpf_clear after mpf_set_prec_raw causes error

### ISSUE THREAD

**Issue by andr1972** [ShiftMediaProject/gmp#2]
My test program(Pi) uses procedure **mpf_set_prec_raw** several times. This procedure 

```
void
mpf_set_prec_raw (mpf_ptr x, mp_bitcnt_t prec_in_bits) __GMP_NOTHROW
{
  x->_mp_prec = __GMPF_BITS_TO_PREC (prec_in_bits);
}
```

only set field _mp_prec and don't manipulate with memory. For example 7 change to 2.
Next, **mpf_clear** calls **__gmp_default_free** with parameter PREC(x) + 1.  
In mode Debug is error when I compile sources of libgmp as standalone exe.  If project is compiled as library (even Debug) no error appears.  Checking magic deadbeef+deafdeed is unnecessary because always will free the same size what is allocated? But what will if user increase precision by mpf_set_prec_raw? I don't know why compiling as library not causes error.

**Comment by andr1972** [comment]
procedure mpf_set_prec_raw  is dangerous for memory allocation and simply better is using **mpf_set_prec** . This mean - error after mpf_set_prec_raw is a normal thing
or set size to start size before clear, for example

```
mpf_set_prec_raw(t1, mpf_get_default_prec()); 
mpf_clear(t1);
```

**Comment by Sibras** [comment]
I wouldnt recommend compiling the gmp source code directly into another application as there are a few things in gmp that need to be handled specifically. Only the use of the static/shared libraries that are provided here are directly supported so make sure you are linking against those. So does your issue appear when linking against the static/shared libs generated by the unmodified supplied project?

So if you find an issue in the msvc libs that appears to be a miscompilation then make sure to let me know, if it appears to actually be an error in the underlying code then your best bet is to submit the bug to the upstream gmp team directly.
