### ISSUE TITLE
gmpxx.h is missing

### ISSUE THREAD

**Issue by zosrothko** [ShiftMediaProject/gmp#4]
## Context
Porting a Linux application that is using gmp on windows

## Expected Behavior
The Linux application is including in several sources `#include <gmpxx.h>`

## Actual Behavior
Include <gmpxx.h> not found

## Steps to Reproduce
Not availabel

## Your Environment
Windows10, VisualStudio 2015

**Comment by Sibras** [comment]
gmpxx.h is the C++ interface header whereas so far this library has only been tested using the standard C interface header. If you want to test to see if the C++ interface works then you can directly copy the missing header from this repository [gmpxx.h](https://raw.githubusercontent.com/ShiftMediaProject/gmp/master/gmpxx.h) and paste it in your include directory. If everything links correctly then let me know and i will update the releases to include gmpxx.h.
