### ISSUE TITLE
In windows x64 build

### ISSUE THREAD

**Issue by byteschain** [ShiftMediaProject/gmp#5]
## Steps to Reproduce

1>alt_bn128_g1.obj : error LNK2019: unresolved external symbol ___gmp_printf referenced in function "public: void __thiscall libsnark::alt_bn128_G1::print(void)const " (?print@alt_bn128_G1@libsnark@@QBEXXZ)
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmp_printf
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_add_n
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_add_n
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_add_n
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_add_n
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_add_n
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_addmul_1
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_addmul_1
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_addmul_1
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_addmul_1
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_addmul_1
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_gcdext
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_gcdext
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_gcdext
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_gcdext
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_gcdext
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_mul_n
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_mul_n
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_mul_n
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_mul_n
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_mul_n
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_sub_n
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_sub_n
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_sub_n
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_sub_n
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_sub_n
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_tdiv_qr
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_tdiv_qr
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_tdiv_qr
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_tdiv_qr
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_tdiv_qr
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_copyi
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_copyi
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_copyi
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_copyi
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_copyi
1>libzsl.obj : error LNK2001: unresolved external symbol ___gmpn_zero
1>alt_bn128_g1.obj : error LNK2001: unresolved external symbol ___gmpn_zero
1>alt_bn128_g2.obj : error LNK2001: unresolved external symbol ___gmpn_zero
1>alt_bn128_init.obj : error LNK2001: unresolved external symbol ___gmpn_zero
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_zero
1>alt_bn128_init.obj : error LNK2019: unresolved external symbol ___gmpn_set_str referenced in function "public: __thiscall libsnark::bigint<4>::bigint<4>(char const *)" (??0?$bigint@$03@libsnark@@QAE@PBD@Z)
1>alt_bn128_pairing.obj : error LNK2001: unresolved external symbol ___gmpn_set_str
1>libzsl.obj : error LNK2019: unresolved external symbol ___gmpn_rshift referenced in function "class std::vector<__int64,class std::allocator<__int64> > __cdecl libsnark::find_wnaf<4>(unsigned __int64,class libsnark::bigint<4> const &)" (??$find_wnaf@$03@libsnark@@YA?AV?$vector@_JV?$allocator@_J@std@@@std@@_KABV?$bigint@$03@0@@Z)
1>..\..\build\win32\dbin\gmp.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
1>E:\work\bubi\project\test_atl_bn128\zsl\build\win32\\dbin\LibZsl.exe : fatal error LNK1120: 11 unresolved externals
1>Done building project "LibZsl.vcxproj" -- FAILED.
## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
You are building a 64bit application but trying to link to a 32bit library. This obviously doesnt work. Link to the correct library to fix it.

**Comment by byteschain** [comment]
I link to a 64bit gmp.lib library.

**Comment by Sibras** [comment]
Well your clearly mixing 32bit and 64bit as per this error.

> 1>....\build\win32\dbin\gmp.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
