### ISSUE TITLE
[VS2019 16.7.2]error MSB3843: Project "libgmp" targets platform "Windows", but references SDK "Visual C++ 2015 Runtime for Universal Windows Platform Apps v14.0" which targets platform "UAP

### ISSUE THREAD

**Issue by PhoebeHui** [ShiftMediaProject/gmp#9]
Hi All,

We found that gmp with x64-uwp failed on vs2019 16.7.2 with following failure:

```
error MSB3843: Project "libgmp" targets platform "Windows", but references SDK "Visual C++ 2015 Runtime for Universal Windows Platform Apps v14.0" which targets platform "UAP"
```

The project configuration is ReleaseDLLWinRT | x64, confirming with msbuild team, that mixing configurations with different application types is not supported, and this has never been supported, not sure why it works before, could you please take a look? thank you in advance!

See repro steps and full failure log in issue https://github.com/microsoft/vcpkg/issues/13172.

Thanks,
Phoebe

**Comment by Sibras** [comment]
Im trying to sort this one out. But im not actually sure what the problem is as clearly some combination of values inside the project file are now suddenly causing an issue.

**Comment by Sibras** [comment]
I still dont know what project options is causing this issue. I cant find anything in the project structure that references Visual Studio 2015 runtime or similar. If you have any further insights or feedback from the msbuild team that would help.

> confirming with msbuild team, that mixing configurations with different application types is not supported

Am i to understand that this means that it is not possible to have a UWP configuration in the same project file as a non-UWP project configuration?

**Comment by PhoebeHui** [comment]
@Sibras, yes, this is not a supported scenario, they advised to contact the owners of this project. I didn't get any further feedback from msbuild team.
